// METROPHAGE — district renderer: turns a DistrictDef (pure data) into a tile grid.
// No Phaser imports: this is the "world model" the renderer consumes. Later AI/sim
// work can read this grid without touching draw code.

import { GRID_W, GRID_H, DISTRICT_SCALE, DISTRICT_GRID_W, DISTRICT_GRID_H, TILE } from "../config";
import { DISTRICTS, type DistrictDef, type Rect } from "../game/districts";
import { DISTRICT_VENUE_COUNT, wildernessShackDef } from "../game/districtVenues";
import { envForDistrict } from "../game/districtEnv";
import {
  type BridgeDef,
  type PathSegment,
  type WildernessBiome,
  travelSpawnTile,
  bridgeWestTile,
  bridgeEastTile,
  getBridge,
} from "../game/bridges";
import {
  TUTORIAL_SPAWN,
  TUTORIAL_PORTAL,
  TUTORIAL_PORTAL_RADIUS,
  TUTORIAL_SPAWN_TILE,
  TUTORIAL_COP_TILE,
  TUTORIAL_NODE_TILE,
  TUTORIAL_PORTAL_TILE,
  tutorialChambers,
  tutorialDividers,
  tutorialGridW,
  tutorialPortalTile,
  tutorialPortalPos,
} from "../game/tutorialLayout";
import type { TutorialMode } from "../net/tutorial";

export {
  TUTORIAL_SPAWN,
  TUTORIAL_PORTAL,
  TUTORIAL_PORTAL_RADIUS,
  TUTORIAL_SPAWN_TILE,
  TUTORIAL_COP_TILE,
  TUTORIAL_NODE_TILE,
  TUTORIAL_PORTAL_TILE,
  tutorialPortalPos,
};

// Indices into the code-authored tileset (textures.ts; 256×128, 32 cells of 32×32).
// Walkable ground 0–3,5,10–14; building/blocking tiles 4,6–9,15 (see isWall).
export const TILE_FLOOR = 0; // concrete, walkable (the default play surface)
export const TILE_SIDEWALK = 1; // paved walkway (borders buildings)
export const TILE_LANE = 2; // road / asphalt, walkable
export const TILE_PLAZA = 3; // neon plaza, walkable
export const TILE_WALL = 4; // DOWNTOWN building, collides
export const TILE_GRASS = 5; // park / green, walkable
export const TILE_WATER = 6; // canal — blocks movement
export const TILE_WALL_IND = 7; // INDUSTRIAL building
export const TILE_WALL_RES = 8; // RESIDENTIAL building
export const TILE_WALL_CORP = 9; // CORPORATE glass tower
export const TILE_MARKET = 10; // market ground, walkable
export const TILE_GRATE = 11; // industrial grating floor, walkable
export const TILE_CROSSWALK = 12; // road crossing, walkable
export const TILE_NEON = 13; // neon-strip floor (nightlife), walkable
export const TILE_DIRT = 14; // wasteland / slum ground, walkable
export const TILE_WALL_SLUM = 15; // shanty building
export const TILE_INNER_FLOOR = 16; // building interior floor (wood/tile), walkable
export const TILE_INNER_WALL = 17; // building interior wall

/** Tiles that block movement (buildings + water). */
const WALL_TILES = new Set<number>([
  TILE_WALL,
  TILE_WATER,
  TILE_WALL_IND,
  TILE_WALL_RES,
  TILE_WALL_CORP,
  TILE_WALL_SLUM,
  TILE_INNER_WALL,
]);

/**
 * Real-art tile VARIANTS (cells 18–31 of the tileset). Each base index maps to the set of
 * interchangeable render tiles (itself + extra swatches of the same surface) that the render
 * variation pass scatters to break visible repetition. Generated by tools/tileset-gen.mjs —
 * keep in sync with the tileset PNG. Collision/gameplay still key off the canonical base index
 * in the grid; only the *rendered* tile index varies (see src/render/tileVariants.ts), so the
 * wall-variant cells (roofs 25–29) must also be marked colliding below.
 */
export const TILE_VARIANTS: Record<number, number[]> = {
  0: [0, 18, 19], 1: [1, 21, 37], 2: [2, 20, 38], 3: [3, 22], 4: [4, 25], 5: [5, 32], 6: [6, 33],
  7: [7, 26], 8: [8, 27], 9: [9, 28], 10: [10, 23], 11: [11, 31], 12: [12, 34], 13: [13, 35], 14: [14, 24],
  15: [15, 29], 16: [16, 30, 39], 17: [17, 36],
};
/** Roof-variant cells (variants of the colliding building bases 4/7/8/9/15). */
const WALL_VARIANTS = [25, 26, 27, 28, 29];
/** Interior-wall variant (base 17) — must still collide when scattered. */
const INNER_WALL_VARIANTS = [36];

/** Deterministic per-tile variant pick (stable across reloads). ~25% of tiles use an
 *  alternate swatch — enough to break repetition without patchwork mismatched photos. */
export function variantOf(base: number, tx: number, ty: number): number {
  const vs = TILE_VARIANTS[base];
  if (!vs || vs.length < 2) return base;
  const h = ((tx * 73856093) ^ (ty * 19349663) ^ (base * 83492791)) >>> 0;
  if ((h & 3) !== 0) return base;
  return vs[1 + (h % (vs.length - 1))];
}

/** Every building/blocking tile index — scenes pass this to setCollision(). Includes the
 *  roof-variant cells so a varied building top still collides. */
export const COLLIDING_TILES: number[] = [...WALL_TILES, ...WALL_VARIANTS, ...INNER_WALL_VARIANTS];

export type TileGrid = number[][];

function gridW(grid: TileGrid) {
  return grid[0]?.length ?? GRID_W;
}
function gridH(grid: TileGrid) {
  return grid.length;
}

function fill(grid: TileGrid, r: Rect, tile: number) {
  const gw = gridW(grid);
  const gh = gridH(grid);
  for (let y = r.y1; y <= r.y2; y++) {
    for (let x = r.x1; x <= r.x2; x++) {
      if (y >= 0 && y < gh && x >= 0 && x < gw) grid[y][x] = tile;
    }
  }
}

const S = DISTRICT_SCALE;
const scaleRect = (r: Rect): Rect => ({ x1: r.x1 * S, y1: r.y1 * S, x2: r.x2 * S, y2: r.y2 * S });
const scaleTile = (t: [number, number]): [number, number] => [t[0] * S, t[1] * S];

/** Carve a single tile (and its 4-neighbours) walkable — keeps key points reachable. */
function carve(grid: TileGrid, tx: number, ty: number, tile = TILE_FLOOR) {
  const gw = gridW(grid);
  const gh = gridH(grid);
  const pts: Array<[number, number]> = [
    [tx, ty],
    [tx - 1, ty],
    [tx + 1, ty],
    [tx, ty - 1],
    [tx, ty + 1],
  ];
  for (const [x, y] of pts) {
    if (x > 0 && x < gw - 1 && y > 0 && y < gh - 1 && isWall(grid[y][x])) {
      grid[y][x] = tile;
    }
  }
}

/** Nearest already-walkable tile to (tx,ty), found by an expanding ring search that
 *  stays inside the outer wall ring. Returns undefined if none within `maxR`. Used so a
 *  travel entry point that lands inside a building footprint snaps to the adjacent street
 *  instead of carving a one-tile pocket that traps the runner on top of the building.
 *
 *  Prefers tiles with at least one walkable neighbour (not a 1-tile pocket). */
function nearestWalkable(grid: TileGrid, tx: number, ty: number, maxR = 20): [number, number] | undefined {
  const gw = gridW(grid);
  const gh = gridH(grid);
  const open = (x: number, y: number) =>
    x > 0 && x < gw - 1 && y > 0 && y < gh - 1 && grid[y]?.[x] !== undefined && !isWall(grid[y][x]);
  const hasOpenNeighbour = (x: number, y: number) =>
    open(x - 1, y) || open(x + 1, y) || open(x, y - 1) || open(x, y + 1);
  const good = (x: number, y: number) => open(x, y) && hasOpenNeighbour(x, y);

  if (good(tx, ty)) return [tx, ty];
  // First pass: prefer well-connected open tiles.
  for (let r = 1; r <= maxR; r++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        if (Math.max(Math.abs(dx), Math.abs(dy)) !== r) continue;
        if (good(tx + dx, ty + dy)) return [tx + dx, ty + dy];
      }
    }
  }
  // Second pass: any open tile (last resort).
  if (open(tx, ty)) return [tx, ty];
  for (let r = 1; r <= maxR; r++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        if (Math.max(Math.abs(dx), Math.abs(dy)) !== r) continue;
        if (open(tx + dx, ty + dy)) return [tx + dx, ty + dy];
      }
    }
  }
  return undefined;
}

/** Build a district's tile grid deterministically from its DistrictDef. */
/**
 * How many authored buildings to place on the combat floor.
 * First {@link DISTRICT_VENUE_COUNT} (5) are unique enterable venues (shop/home/guild/den/bar);
 * extras are scenery-only blocks (district-kit roofs, no door — no duplicate shop/bar).
 */
export const DISTRICT_BUILDING_CAP = 9;
/** The buildings a district actually uses (first N). Shared by the grid builder and the
 *  client's door/façade passes so walls, doorways and roofs all agree on the same set. */
export function districtBuildings(def: DistrictDef): Rect[] {
  return def.layout.buildings.slice(0, DISTRICT_BUILDING_CAP);
}
/** Indices that get an enterable door (one of each venue kind). */
export function districtEnterableIndices(def: DistrictDef): number[] {
  const n = Math.min(DISTRICT_VENUE_COUNT, districtBuildings(def).length);
  return Array.from({ length: n }, (_, i) => i);
}

export function buildGrid(def: DistrictDef = DISTRICTS[0]): TileGrid {
  const gw = DISTRICT_GRID_W;
  const gh = DISTRICT_GRID_H;
  const env = envForDistrict(def.id);
  const gnd = env.ground;
  const grid: TileGrid = [];
  // Themed base floor — each district has its own surface language.
  for (let y = 0; y < gh; y++) {
    grid.push(new Array(gw).fill(gnd.floor));
  }
  // Occasional sidewalk / edge scatter so mono floors don't read as a flat sheet.
  if (gnd.sidewalkChance > 0) {
    for (let y = 1; y < gh - 1; y++) {
      for (let x = 1; x < gw - 1; x++) {
        const h = ((x * 73856093) ^ (y * 19349663) ^ (def.id.length * 83492791)) >>> 0;
        if ((h % 1000) / 1000 < gnd.sidewalkChance) grid[y][x] = gnd.sidewalk;
      }
    }
  }

  // Outer wall ring — use primary roof material so the ring matches the district.
  const border = gnd.roofs[0] ?? TILE_WALL;
  for (let x = 0; x < gw; x++) {
    grid[0][x] = border;
    grid[gh - 1][x] = border;
  }
  for (let y = 0; y < gh; y++) {
    grid[y][0] = border;
    grid[y][gw - 1] = border;
  }

  const { plaza, laneRows, laneCols } = def.layout;
  const buildings = districtBuildings(def); // capped for a more open, less maze-dense combat floor
  const ROOF_CYCLE = gnd.roofs.length ? gnd.roofs : [TILE_WALL, TILE_WALL_CORP, TILE_WALL_RES, TILE_WALL_IND, TILE_WALL_SLUM];
  buildings.forEach((b, i) => fill(grid, scaleRect(b), ROOF_CYCLE[i % ROOF_CYCLE.length]));
  if (plaza) fill(grid, scaleRect(plaza), gnd.plaza);

  for (const y of laneRows) {
    const sy = y * S;
    if (sy <= 0 || sy >= gh - 1) continue;
    for (let x = 1; x < gw - 1; x++) {
      // Lane over any themed floor (not just TILE_FLOOR).
      if (!isWall(grid[sy][x]) && grid[sy][x] !== gnd.plaza) grid[sy][x] = gnd.lane;
    }
  }
  for (const x of laneCols) {
    const sx = x * S;
    if (sx <= 0 || sx >= gw - 1) continue;
    for (let y = 1; y < gh - 1; y++) {
      if (!isWall(grid[y][sx]) && grid[y][sx] !== gnd.plaza) grid[y][sx] = gnd.lane;
    }
  }

  // Open critical points with the district's walkable floor (not a generic concrete).
  const walk = gnd.floor;
  carve(grid, ...scaleTile(def.spawnTile), walk);
  carve(grid, ...scaleTile(def.diveTile), walk);
  carve(grid, ...scaleTile(def.boardTile), walk);
  carve(grid, ...scaleTile(def.shopTile), walk);
  for (const n of def.nodes) carve(grid, ...scaleTile(n.tile), walk);

  return grid;
}

const bridgeHash = (x: number, y: number, salt = 0) => ((x * 9283711) ^ (y * 6892871) ^ salt) >>> 0;

type BiomeStyle = { path: number; flank: number; ruin: number; clearing: number; border: number };

const BIOME_STYLE: Record<WildernessBiome, BiomeStyle> = {
  ruined_urban: { path: TILE_LANE, flank: TILE_SIDEWALK, ruin: TILE_WALL, clearing: TILE_PLAZA, border: TILE_WALL_SLUM },
  industrial_cut: { path: TILE_GRATE, flank: TILE_DIRT, ruin: TILE_WALL_IND, clearing: TILE_MARKET, border: TILE_WALL_IND },
  floodplain: { path: TILE_DIRT, flank: TILE_GRASS, ruin: TILE_WALL_SLUM, clearing: TILE_GRASS, border: TILE_WALL_SLUM },
  undercity: { path: TILE_DIRT, flank: TILE_NEON, ruin: TILE_WALL_CORP, clearing: TILE_NEON, border: TILE_WALL_CORP },
  debris_field: { path: TILE_DIRT, flank: TILE_GRASS, ruin: TILE_WALL_IND, clearing: TILE_MARKET, border: TILE_WALL_IND },
  ash_wastes: { path: TILE_DIRT, flank: TILE_DIRT, ruin: TILE_WALL_SLUM, clearing: TILE_NEON, border: TILE_WALL_SLUM },
  meltdown: { path: TILE_NEON, flank: TILE_DIRT, ruin: TILE_WALL, clearing: TILE_PLAZA, border: TILE_WALL },
};

function wildBaseTile(biome: WildernessBiome, x: number, y: number, salt: number): number {
  const h = bridgeHash(x, y, salt);
  switch (biome) {
    case "ruined_urban":
      if (h % 13 === 0) return TILE_SIDEWALK;
      if (h % 9 === 0) return TILE_GRASS;
      return TILE_DIRT;
    case "industrial_cut":
      if (h % 11 === 0) return TILE_GRATE;
      return h % 6 === 0 ? TILE_GRASS : TILE_DIRT;
    case "floodplain":
      return h % 4 === 0 ? TILE_DIRT : TILE_GRASS;
    case "undercity":
      if (h % 17 === 0) return TILE_NEON;
      return h % 5 === 0 ? TILE_GRASS : TILE_DIRT;
    case "debris_field":
      if (h % 10 === 0) return TILE_MARKET;
      return h % 4 === 0 ? TILE_GRASS : TILE_DIRT;
    case "ash_wastes":
      if (h % 19 === 0) return TILE_GRASS;
      if (h % 23 === 0) return TILE_NEON;
      return TILE_DIRT;
    case "meltdown":
      if (h % 15 === 0) return TILE_NEON;
      if (h % 9 === 0) return TILE_PLAZA;
      return TILE_DIRT;
  }
}

function paintPathStrip(grid: TileGrid, seg: PathSegment, style: BiomeStyle, width = 2) {
  const gw = gridW(grid);
  const gh = gridH(grid);
  const sy = seg.y * S;
  const x0 = Math.max(1, seg.x1 * S);
  const x1 = Math.min(gw - 2, seg.x2 * S);
  if (sy <= 0 || sy >= gh - 1) return;
  for (let x = x0; x <= x1; x++) {
    for (let dy = -width; dy <= width; dy++) {
      const ry = sy + dy;
      if (ry <= 0 || ry >= gh - 1) continue;
      if (isWall(grid[ry][x])) continue;
      grid[ry][x] = dy === 0 ? style.path : style.flank;
    }
  }
}

function connectPathSegments(grid: TileGrid, segments: PathSegment[], style: BiomeStyle) {
  for (let i = 0; i < segments.length - 1; i++) {
    const a = segments[i];
    const b = segments[i + 1];
    const overlapX0 = Math.max(a.x1, b.x1);
    const overlapX1 = Math.min(a.x2, b.x2);
    if (overlapX0 > overlapX1) continue;
    const xMid = Math.floor(((overlapX0 + overlapX1) / 2) * S);
    const y0 = Math.min(a.y, b.y) * S;
    const y1 = Math.max(a.y, b.y) * S;
    for (let y = y0; y <= y1; y++) {
      for (let dx = -1; dx <= 1; dx++) {
        const x = xMid + dx;
        if (x <= 0 || x >= gridW(grid) - 1) continue;
        if (isWall(grid[y]?.[x])) continue;
        grid[y][x] = dx === 0 ? style.path : style.flank;
      }
    }
  }
}

/** Wilderness corridor between two districts — biome-specific ground, winding trails, ruins. */
export function buildBridgeGrid(def: BridgeDef = getBridge(0)): TileGrid {
  const gw = DISTRICT_GRID_W;
  const gh = DISTRICT_GRID_H;
  const biome = def.layout.biome;
  const style = BIOME_STYLE[biome];
  const salt = def.fromDistrict * 31337 + 17;
  const grid: TileGrid = [];
  for (let y = 0; y < gh; y++) {
    const row: number[] = [];
    for (let x = 0; x < gw; x++) {
      row.push(wildBaseTile(biome, x, y, salt));
    }
    grid.push(row);
  }
  for (let x = 0; x < gw; x++) {
    grid[0][x] = style.border;
    grid[gh - 1][x] = style.border;
  }
  for (let y = 0; y < gh; y++) {
    grid[y][0] = style.border;
    grid[y][gw - 1] = style.border;
  }
  for (const g of def.layout.groves) fill(grid, scaleRect(g), TILE_GRASS);
  for (const c of def.layout.clearings ?? []) fill(grid, scaleRect(c), style.clearing);
  for (const r of def.layout.ruins) fill(grid, scaleRect(r), style.ruin);
  for (const h of def.layout.hazards) fill(grid, scaleRect(h), TILE_WATER);

  const segments =
    def.layout.pathSegments ??
    def.layout.pathRows.map((y) => ({ y, x1: 2, x2: 38 }));
  for (const seg of segments) paintPathStrip(grid, seg, style);
  if (segments.length > 1) connectPathSegments(grid, segments, style);
  if (def.layout.spur) paintPathStrip(grid, def.layout.spur, style, 1);

  const [wx, wy] = bridgeWestTile(def);
  const [ex, ey] = bridgeEastTile(def);
  carve(grid, wx, wy, style.path);
  carve(grid, ex, ey, style.path);
  carve(grid, ...scaleTile(def.guideTile), style.flank);
  return grid;
}

/** True for wall tiles. Missing / OOB tiles (`undefined`/`NaN`) count as walls so
 *  spawn guards like `if (isWall(grid[y]?.[x])) continue` actually skip them. */
export function isWall(tile: number | undefined | null): boolean {
  if (tile == null || !Number.isFinite(tile)) return true;
  return WALL_TILES.has(tile);
}

/**
 * The SAFEHOUSE interior — a walled room of warm interior floor: a server-authoritative,
 * no-combat social hub (+ vendor) players enter from any district. Shared by the client
 * (renders it) and the server (sims zone "safe"). Same world bounds as a district so the
 * camera/physics need no special-casing.
 */
export function buildSafehouse(): TileGrid {
  const g: TileGrid = [];
  for (let y = 0; y < GRID_H; y++) {
    const row: number[] = [];
    for (let x = 0; x < GRID_W; x++) {
      const border = x < 4 || x >= GRID_W - 4 || y < 3 || y >= GRID_H - 3;
      row.push(border ? TILE_INNER_WALL : TILE_INNER_FLOOR);
    }
    g.push(row);
  }
  // interior pillars for character (all collide)
  for (const [px, py] of [[12, 10], [27, 10], [12, 20], [27, 20]] as const) {
    g[py][px] = TILE_INNER_WALL;
    g[py][px + 1] = TILE_INNER_WALL;
  }
  return g;
}

/** Centre of the safehouse (open floor) — the spawn / return point, in world pixels. */
export const SAFEHOUSE_SPAWN = {
  x: Math.floor(GRID_W / 2) * TILE + TILE / 2,
  y: Math.floor(GRID_H / 2) * TILE + TILE / 2,
};

/**
 * FRLG-style venue rooms — building interiors at Pokémon-house scale, with a
 * service counter and a door mat against the south wall. You appear one step
 * above the mat; stepping DOWN onto it walks you out.
 *
 * Every d{N}i{K} / h{K} building picks ONE of several floor plans, chosen by a
 * deterministic hash of its zone id, so the client and server always build the
 * IDENTICAL grid (collision is server-authoritative) and a given door always
 * opens on the same room. est{K} player homes are pinned to the classic STUDIO
 * plan forever — placed furniture persists tile coordinates.
 */
export const VENUE_ROOM_W = 15;
export const VENUE_ROOM_H = 11;
/** The classic room's exit mat — est{K} furniture code + home rooms key off this. */
export const VENUE_MAT_TILE: [number, number] = [7, 9];
/** Classic arrival point — one step above the mat (walking down = leaving). */
export const VENUE_SPAWN = {
  x: VENUE_MAT_TILE[0] * TILE + TILE / 2,
  y: (VENUE_MAT_TILE[1] - 1) * TILE + TILE / 2,
};

export interface VenueLayout {
  w: number;
  h: number;
  /** Exit mat tile on the south wall. */
  mat: [number, number];
  /** Walkable spots for occupants + service NPCs, spread around the plan. */
  seats: Array<[number, number]>;
  /** Service counter: wall run along row `y`, x0..x1, with a pass-through gap. */
  counter: { x0: number; x1: number; y: number; gap: number };
  /** Extra interior wall blocks (inclusive tile rects): pillars, partitions, islands. */
  blocks?: Array<[number, number, number, number]>;
  /** Flavor tag for the client dresser. */
  tag: "studio" | "loft" | "hall" | "backroom" | "atrium";
}

/** Index 0 MUST stay byte-identical to the original 15×11 room (est homes use it). */
export const VENUE_LAYOUTS: VenueLayout[] = [
  {
    // STUDIO — the classic one-counter room
    w: 15, h: 11, mat: [7, 9], tag: "studio",
    counter: { x0: 4, x1: 10, y: 3, gap: 7 },
    seats: [[7, 2], [4, 5], [10, 5], [11, 7]],
  },
  {
    // LOFT — wide room, pillar pairs split a lounge off the counter run
    w: 21, h: 13, mat: [10, 11], tag: "loft",
    counter: { x0: 3, x1: 9, y: 3, gap: 6 },
    blocks: [[13, 5, 14, 6], [17, 8, 18, 9]],
    seats: [[6, 2], [4, 6], [15, 4], [16, 11], [11, 7]],
  },
  {
    // HALL — long bar along the north wall, booth dividers make alcoves
    w: 27, h: 11, mat: [13, 9], tag: "hall",
    counter: { x0: 3, x1: 23, y: 3, gap: 13 },
    blocks: [[6, 6, 6, 8], [19, 6, 19, 8]],
    seats: [[13, 2], [4, 6], [9, 7], [22, 6], [17, 7]],
  },
  {
    // BACKROOM — front-of-house + a stockroom through a doorway
    w: 19, h: 15, mat: [9, 13], tag: "backroom",
    counter: { x0: 4, x1: 12, y: 9, gap: 9 },
    blocks: [[1, 5, 7, 5], [11, 5, 17, 5]],
    seats: [[9, 8], [3, 11], [15, 11], [4, 2], [14, 2]],
  },
  {
    // ATRIUM — big floor, central planter island, counter in the north-east
    w: 23, h: 17, mat: [11, 15], tag: "atrium",
    counter: { x0: 13, x1: 20, y: 3, gap: 17 },
    blocks: [[8, 7, 13, 9], [3, 11, 4, 12], [18, 11, 19, 12]],
    seats: [[17, 2], [5, 4], [3, 8], [19, 14], [11, 11]],
  },
];

/** djb2 — tiny, stable, identical on client + server (no Math.random anywhere). */
function venueHash(zone: string): number {
  let h = 5381;
  for (let i = 0; i < zone.length; i++) h = ((h << 5) + h + zone.charCodeAt(i)) >>> 0;
  return h;
}

/** The floor plan for a venue-sized zone. est{K} homes are pinned to STUDIO. */
export function venueLayoutFor(zone?: string | null): VenueLayout {
  if (zone && /^(d\d+i\d+|h\d+)$/.test(zone)) {
    return VENUE_LAYOUTS[venueHash(zone) % VENUE_LAYOUTS.length];
  }
  return VENUE_LAYOUTS[0];
}

/** Arrival point for a venue zone — one step above that plan's exit mat.
 *  When `grid` is provided, snaps off any wall/furniture that would trap the runner. */
export function venueSpawnFor(zone?: string | null, grid?: TileGrid): { x: number; y: number } {
  const L = venueLayoutFor(zone);
  // Prefer one step *north* of the exit mat (into the room), then around the mat.
  const candidates: Array<[number, number]> = [
    [L.mat[0], L.mat[1] - 1],
    [L.mat[0], L.mat[1] - 2],
    [L.mat[0] - 1, L.mat[1] - 1],
    [L.mat[0] + 1, L.mat[1] - 1],
    [L.mat[0], L.mat[1]],
  ];
  if (!grid) {
    const [tx, ty] = candidates[0];
    return { x: tx * TILE + TILE / 2, y: ty * TILE + TILE / 2 };
  }
  for (const [tx, ty] of candidates) {
    if (grid[ty]?.[tx] !== undefined && !isWall(grid[ty][tx])) {
      return { x: tx * TILE + TILE / 2, y: ty * TILE + TILE / 2 };
    }
  }
  // Mat area blocked (odd plan) — search whole room.
  const near = nearestWalkable(grid, L.mat[0], L.mat[1] - 1, Math.max(L.w, L.h));
  if (near) return { x: near[0] * TILE + TILE / 2, y: near[1] * TILE + TILE / 2 };
  return { x: L.mat[0] * TILE + TILE / 2, y: (L.mat[1] - 1) * TILE + TILE / 2 };
}

export function buildVenueRoomFromLayout(L: VenueLayout): TileGrid {
  const g: TileGrid = [];
  for (let y = 0; y < L.h; y++) {
    const row: number[] = [];
    for (let x = 0; x < L.w; x++) {
      const border = x === 0 || x === L.w - 1 || y === 0 || y === L.h - 1;
      row.push(border ? TILE_INNER_WALL : TILE_INNER_FLOOR);
    }
    g.push(row);
  }
  // service counter — the keeper stands behind it, customers in front
  for (let x = L.counter.x0; x <= L.counter.x1; x++) g[L.counter.y][x] = TILE_INNER_WALL;
  g[L.counter.y][L.counter.gap] = TILE_INNER_FLOOR; // pass-through keeps the far side reachable
  for (const [x0, y0, x1, y1] of L.blocks ?? []) {
    for (let y = y0; y <= y1; y++) {
      for (let x = x0; x <= x1; x++) g[y][x] = TILE_INNER_WALL;
    }
  }
  return g;
}

export function buildVenueRoom(zone?: string): TileGrid {
  return buildVenueRoomFromLayout(venueLayoutFor(zone));
}

/**
 * THE UNDERLINE — massive campaign-map subway (see world/subway.ts).
 * Re-exported here so existing client/server imports keep working.
 */
export { buildSubway, SUBWAY_SPAWN } from "./subway";

/**
 * ICE VAULT — the instanced dive dungeon (one per district, zones v0–v6). A frozen-mind
 * storage vault: entry hall → split guard chambers → antechamber → the core chamber
 * where a memory fragment is channelled free (the fragment core reuses the territory-
 * node channel mechanic). Shared by client render and server sim.
 */
export const DIVE_ZONE_IDS = ["v0", "v1", "v2", "v3", "v4", "v5", "v6", "v7"] as const;
/** v0–v6 → district index, or -1 when the zone isn't a dive. */
export function parseDiveZone(zone: string | null | undefined): number {
  if (!zone || zone[0] !== "v") return -1;
  const n = Number(zone.slice(1));
  return Number.isInteger(n) && n >= 0 && n < DIVE_ZONE_IDS.length ? n : -1;
}

export function buildDive(): TileGrid {
  const g: TileGrid = [];
  for (let y = 0; y < GRID_H; y++) {
    const row: number[] = [];
    for (let x = 0; x < GRID_W; x++) row.push(TILE_INNER_WALL);
    g.push(row);
  }
  const room = (x0: number, y0: number, x1: number, y1: number) => {
    for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) g[y][x] = TILE_INNER_FLOOR;
  };
  room(2, 12, 8, 18); // entry hall (spawn + surface exit)
  room(8, 14, 20, 16); // west corridor
  room(11, 6, 19, 11); // north guard chamber
  room(11, 19, 19, 24); // south guard chamber
  room(14, 11, 16, 19); // connector between chambers, crossing the corridor
  room(20, 13, 25, 17); // antechamber
  room(25, 9, 37, 21); // core chamber
  return g;
}
export const DIVE_SPAWN = { x: 4 * TILE + TILE / 2, y: 15 * TILE + TILE / 2 };
/** The fragment core sits deep in the core chamber. */
export const DIVE_CORE_TILE: [number, number] = [33, 15];

/**
 * THE DRILL YARD — linear training facility with distinct west→east chambers.
 * Shared by client render and server sim (zone "tutorial" / "tutorial_full").
 * Full training uses a longer systems hall so every instructor has room.
 */
export function buildTutorial(mode: TutorialMode = "quick"): TileGrid {
  const gw = tutorialGridW(mode);
  const gh = GRID_H;
  const chambers = tutorialChambers(mode);
  const dividers = tutorialDividers(mode);
  const portalTx = tutorialPortalTile(mode)[0];
  const g: TileGrid = [];
  for (let y = 0; y < gh; y++) {
    const row: number[] = [];
    for (let x = 0; x < gw; x++) {
      const border = x < 3 || x >= gw - 3 || y < 2 || y >= gh - 2;
      row.push(border ? TILE_INNER_WALL : TILE_INNER_FLOOR);
    }
    g.push(row);
  }
  for (const ch of chambers) {
    for (let y = ch.y1; y <= ch.y2; y++) {
      for (let x = ch.x1; x <= ch.x2; x++) {
        if (g[y]?.[x] !== TILE_INNER_WALL) g[y][x] = ch.floor;
      }
    }
  }
  // Main corridor to the deploy gate (extends further in full training).
  for (let x = 4; x <= portalTx; x++) {
    for (let y = 14; y <= 16; y++) {
      if (g[y]?.[x] !== undefined && g[y][x] !== TILE_INNER_WALL) g[y][x] = TILE_CROSSWALK;
    }
  }
  for (const dx of dividers) {
    for (let y = 5; y <= 25; y++) {
      if (y >= 14 && y <= 16) continue;
      if (g[y]?.[dx] !== undefined) g[y][dx] = TILE_INNER_WALL;
    }
  }
  return g;
}

/** Player start in world (pixel) coordinates, at tile center, from the district def. */
export function spawnPoint(grid: TileGrid, def: DistrictDef = DISTRICTS[0]): { x: number; y: number } {
  // Lazy import avoided: resolve via dynamic so sim (which imports district) stays cycle-safe.
  // Callers that need full radius safety should wrap with resolveOpenSpawn from net/sim.
  const [sx, sy] = scaleTile(def.spawnTile);
  const open = nearestWalkable(grid, sx, sy, 24);
  if (open) return { x: open[0] * TILE + TILE / 2, y: open[1] * TILE + TILE / 2 };
  const gw = gridW(grid);
  const gh = gridH(grid);
  for (let y = 1; y < gh - 1; y++) {
    for (let x = 1; x < gw - 1; x++) {
      if (!isWall(grid[y][x])) {
        return { x: x * TILE + TILE / 2, y: y * TILE + TILE / 2 };
      }
    }
  }
  return { x: TILE * 1.5, y: TILE * 1.5 };
}

/** True for FRLG-scale one-screen rooms (15×11 venue / home). */
export function isVenueSizedZone(zone: string | null | undefined): boolean {
  if (!zone) return false;
  // District venues, hub buildings, estate homes, and wilderness trail shacks.
  return /^d\d+i\d+$/.test(zone) || /^h\d+$/.test(zone) || /^est\d+$/.test(zone) || /^w\d+s\d+$/.test(zone);
}

/** Hub service rooms that reuse the full safehouse floor plan. */
export function isSafehouseSizedInterior(zone: string | null | undefined): boolean {
  return zone === "clinic" || zone === "bar" || zone === "den" || zone === "shop" || zone === "vault";
}

/** Spawn at a trail gate when entering from another zone; falls back to the zone's
 *  canonical spawn (when the caller knows it), then the district spawn.
 *  Always returns a candidate — callers MUST run resolveOpenSpawn (net/sim) for
 *  player-radius safety; server login does this as a hard guarantee. */
export function spawnPointForTravel(
  grid: TileGrid,
  zone: string,
  fromZone: string | undefined,
  def?: DistrictDef,
  zoneSpawn?: { x: number; y: number },
): { x: number; y: number } {
  let raw: { x: number; y: number };

  // Compact venue rooms (district buildings, hub buildings, estate homes) — always the
  // mat-adjacent entry tile OF THAT ZONE'S FLOOR PLAN. Using district/safehouse coords
  // here put runners outside the walls after walking in.
  if (isVenueSizedZone(zone)) {
    raw = venueSpawnFor(zone, grid);
  } else if (isSafehouseSizedInterior(zone)) {
    // Named hub service interiors (clinic/bar/den/shop/vault) use the large safehouse plan.
    const open = nearestWalkable(
      grid,
      Math.floor(SAFEHOUSE_SPAWN.x / TILE),
      Math.floor(SAFEHOUSE_SPAWN.y / TILE),
      16,
    );
    raw = open
      ? { x: open[0] * TILE + TILE / 2, y: open[1] * TILE + TILE / 2 }
      : { x: SAFEHOUSE_SPAWN.x, y: SAFEHOUSE_SPAWN.y };
  } else {
    raw = { x: TILE * 1.5, y: TILE * 1.5 };
    let found = false;
    // stepping OUT of a district building interior ("d{N}i{K}") — arrive at that building's
    // doorstep, the same street tile its door portal occupies (mirrors the client's door math)
    const bm = fromZone ? /^d(\d+)i(\d+)$/.exec(fromZone) : null;
    if (bm && def && zone === `d${bm[1]}`) {
      const b = def.layout.buildings[parseInt(bm[2], 10)];
      if (b) {
        const tx = Math.round((b.x1 + b.x2) / 2) * S;
        const ty = b.y2 * S + 1;
        // Prefer a walkable tile SOUTH of the building — never inside the footprint.
        const candidates: Array<[number, number]> = [
          [tx, ty + 1],
          [tx, ty + 2],
          [tx - 1, ty + 1],
          [tx + 1, ty + 1],
          [tx, ty],
          [tx, ty + 3],
        ];
        for (const [cx, cy] of candidates) {
          if (grid[cy]?.[cx] !== undefined && !isWall(grid[cy][cx])) {
            raw = { x: cx * TILE + TILE / 2, y: cy * TILE + TILE / 2 };
            found = true;
            break;
          }
        }
        if (!found) {
          const near = nearestWalkable(grid, tx, ty + 1, 16);
          if (near) {
            raw = { x: near[0] * TILE + TILE / 2, y: near[1] * TILE + TILE / 2 };
            found = true;
          }
        }
      }
    }
    // Leaving a wilderness trail shack ("w{N}s{K}") — land on that shack's doorstep.
    const wsm = fromZone ? /^w(\d+)s(\d+)$/.exec(fromZone) : null;
    if (!found && wsm && zone === `w${wsm[1]}`) {
      const sh = wildernessShackDef(parseInt(wsm[1], 10), parseInt(wsm[2], 10));
      if (sh) {
        const tx = sh.door[0] * S;
        const ty = sh.door[1] * S;
        const candidates: Array<[number, number]> = [
          [tx, ty],
          [tx, ty + 1],
          [tx - 1, ty],
          [tx + 1, ty],
          [tx, ty + 2],
        ];
        for (const [cx, cy] of candidates) {
          if (grid[cy]?.[cx] !== undefined && !isWall(grid[cy][cx])) {
            raw = { x: cx * TILE + TILE / 2, y: cy * TILE + TILE / 2 };
            found = true;
            break;
          }
        }
        if (!found) {
          const near = nearestWalkable(grid, tx, ty, 16);
          if (near) {
            raw = { x: near[0] * TILE + TILE / 2, y: near[1] * TILE + TILE / 2 };
            found = true;
          }
        }
      }
    }
    if (!found) {
      const tile = travelSpawnTile(zone, fromZone);
      if (tile) {
        // Authored entry can land on a building roof — snap to nearest open street.
        const open = nearestWalkable(grid, tile[0], tile[1], 28);
        if (open) {
          raw = { x: open[0] * TILE + TILE / 2, y: open[1] * TILE + TILE / 2 };
          found = true;
        }
      }
    }
    if (!found && zoneSpawn) {
      const tx = Math.floor(zoneSpawn.x / TILE);
      const ty = Math.floor(zoneSpawn.y / TILE);
      const open = nearestWalkable(grid, tx, ty, 28);
      if (open) {
        raw = { x: open[0] * TILE + TILE / 2, y: open[1] * TILE + TILE / 2 };
        found = true;
      } else {
        raw = { x: zoneSpawn.x, y: zoneSpawn.y };
        found = true;
      }
    }
    if (!found && def) {
      raw = spawnPoint(grid, def);
      found = true;
    }
    if (!found) {
      // Last resort: first walkable tile on this grid.
      const gw = gridW(grid);
      const gh = gridH(grid);
      outer: for (let y = 1; y < gh - 1; y++) {
        for (let x = 1; x < gw - 1; x++) {
          if (!isWall(grid[y][x])) {
            raw = { x: x * TILE + TILE / 2, y: y * TILE + TILE / 2 };
            found = true;
            break outer;
          }
        }
      }
    }
    if (!found) {
      const [wx, wy] = bridgeWestTile(getBridge(0));
      const open = nearestWalkable(grid, wx, wy, 12);
      raw = open
        ? { x: open[0] * TILE + TILE / 2, y: open[1] * TILE + TILE / 2 }
        : { x: wx * TILE + TILE / 2, y: wy * TILE + TILE / 2 };
    }
  }

  return raw;
}
